### ISSUE TITLE
Cannot reproduce results for locations

### ISSUE THREAD

**Issue by cybershiptrooper** [choidami/inductive-oocr#2]
When trying to run icl evaluations for locations (using `python launch.py --config_file configs/locations_eval_gpt35.py -f evaluate --run_type ic_baseline`), I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/locations_finetune_gpt35/major_dist_dir_card_2k_200k_500num_5aug_32bs_10lrm_1ne_0/train_data_config.yaml'
```

Looks like an experiments folder is missing?

**Comment by choidami** [comment]
The evaluation commands assume that the fine-tuning command has been launched, since fine-tuning generates the training data required for evaluation.
If you just want to generate the training data, you can edit launch_job to False here in the fine-tuning [config](https://github.com/choidami/inductive-oocr/blob/main/locations/configs/locations_finetune_gpt35.py#L79).
